//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DirectoryPath {
            get {
                return ((string)(this["DirectoryPath"]));
            }
            set {
                this["DirectoryPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public bool LivePreview {
            get {
                return ((bool)(this["LivePreview"]));
            }
            set {
                this["LivePreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupPath {
            get {
                return ((string)(this["BackupPath"]));
            }
            set {
                this["BackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveTimestamps {
            get {
                return ((bool)(this["RemoveTimestamps"]));
            }
            set {
                this["RemoveTimestamps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckForUpdatesAutomatically {
            get {
                return ((bool)(this["CheckForUpdatesAutomatically"]));
            }
            set {
                this["CheckForUpdatesAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BackupChatLogAutomatically {
            get {
                return ((bool)(this["BackupChatLogAutomatically"]));
            }
            set {
                this["BackupChatLogAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableIntervalBackup {
            get {
                return ((bool)(this["EnableIntervalBackup"]));
            }
            set {
                this["EnableIntervalBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveTimestampsFromBackup {
            get {
                return ((bool)(this["RemoveTimestampsFromBackup"]));
            }
            set {
                this["RemoveTimestampsFromBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int IntervalTime {
            get {
                return ((int)(this["IntervalTime"]));
            }
            set {
                this["IntervalTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveTimestampsFromFilter {
            get {
                return ((bool)(this["RemoveTimestampsFromFilter"]));
            }
            set {
                this["RemoveTimestampsFromFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilterNames {
            get {
                return ((string)(this["FilterNames"]));
            }
            set {
                this["FilterNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartWithWindows {
            get {
                return ((bool)(this["StartWithWindows"]));
            }
            set {
                this["StartWithWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuppressNotifications {
            get {
                return ((bool)(this["SuppressNotifications"]));
            }
            set {
                this["SuppressNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string LanguageCode {
            get {
                return ((string)(this["LanguageCode"]));
            }
            set {
                this["LanguageCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasPickedLanguage {
            get {
                return ((bool)(this["HasPickedLanguage"]));
            }
            set {
                this["HasPickedLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int UpdateCheckTimeout {
            get {
                return ((int)(this["UpdateCheckTimeout"]));
            }
            set {
                this["UpdateCheckTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisableForumsButton {
            get {
                return ((bool)(this["DisableForumsButton"]));
            }
            set {
                this["DisableForumsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisableFacebrowserButton {
            get {
                return ((bool)(this["DisableFacebrowserButton"]));
            }
            set {
                this["DisableFacebrowserButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisableUCPButton {
            get {
                return ((bool)(this["DisableUCPButton"]));
            }
            set {
                this["DisableUCPButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisableReleasesButton {
            get {
                return ((bool)(this["DisableReleasesButton"]));
            }
            set {
                this["DisableReleasesButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisableProjectButton {
            get {
                return ((bool)(this["DisableProjectButton"]));
            }
            set {
                this["DisableProjectButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableDiscordButton {
            get {
                return ((bool)(this["DisableDiscordButton"]));
            }
            set {
                this["DisableDiscordButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableShortcutButton {
            get {
                return ((bool)(this["DisableShortcutButton"]));
            }
            set {
                this["DisableShortcutButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DarkMode {
            get {
                return ((bool)(this["DarkMode"]));
            }
            set {
                this["DarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableInformationPopups {
            get {
                return ((bool)(this["DisableInformationPopups"]));
            }
            set {
                this["DisableInformationPopups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableWarningPopups {
            get {
                return ((bool)(this["DisableWarningPopups"]));
            }
            set {
                this["DisableWarningPopups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableErrorPopups {
            get {
                return ((bool)(this["DisableErrorPopups"]));
            }
            set {
                this["DisableErrorPopups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysCloseToTray {
            get {
                return ((bool)(this["AlwaysCloseToTray"]));
            }
            set {
                this["AlwaysCloseToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastParsedAutoHash {
            get {
                return ((string)(this["LastParsedAutoHash"]));
            }
            set {
                this["LastParsedAutoHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IgnoreBetaVersions {
            get {
                return ((bool)(this["IgnoreBetaVersions"]));
            }
            set {
                this["IgnoreBetaVersions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FollowSystemMode {
            get {
                return ((bool)(this["FollowSystemMode"]));
            }
            set {
                this["FollowSystemMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FollowSystemColor {
            get {
                return ((bool)(this["FollowSystemColor"]));
            }
            set {
                this["FollowSystemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SameHashAutoCount {
            get {
                return ((int)(this["SameHashAutoCount"]));
            }
            set {
                this["SameHashAutoCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OtherCriterionEnabled {
            get {
                return ((bool)(this["OtherCriterionEnabled"]));
            }
            set {
                this["OtherCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OOCCriterionEnabled {
            get {
                return ((bool)(this["OOCCriterionEnabled"]));
            }
            set {
                this["OOCCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ICCriterionEnabled {
            get {
                return ((bool)(this["ICCriterionEnabled"]));
            }
            set {
                this["ICCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmoteCriterionEnabled {
            get {
                return ((bool)(this["EmoteCriterionEnabled"]));
            }
            set {
                this["EmoteCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActionCriterionEnabled {
            get {
                return ((bool)(this["ActionCriterionEnabled"]));
            }
            set {
                this["ActionCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PMCriterionEnabled {
            get {
                return ((bool)(this["PMCriterionEnabled"]));
            }
            set {
                this["PMCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RadioCriterionEnabled {
            get {
                return ((bool)(this["RadioCriterionEnabled"]));
            }
            set {
                this["RadioCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdsCriterionEnabled {
            get {
                return ((bool)(this["AdsCriterionEnabled"]));
            }
            set {
                this["AdsCriterionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SameHashWarnAmount {
            get {
                return ((int)(this["SameHashWarnAmount"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WarnOnSameHash {
            get {
                return ((bool)(this["WarnOnSameHash"]));
            }
            set {
                this["WarnOnSameHash"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BackupFormat {
            get {
                return ((int)(this["BackupFormat"]));
            }
            set {
                this["BackupFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDetectServerTimezone {
            get {
                return ((bool)(this["AutoDetectServerTimezone"]));
            }
            set {
                this["AutoDetectServerTimezone"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTC")]
        public string ServerTimezone {
            get {
                return ((string)(this["ServerTimezone"]));
            }
            set {
                this["ServerTimezone"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string ScreenshotFontFamily {
            get {
                return ((string)(this["ScreenshotFontFamily"]));
            }
            set {
                this["ScreenshotFontFamily"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double ScreenshotFontSize {
            get {
                return ((double)(this["ScreenshotFontSize"]));
            }
            set {
                this["ScreenshotFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double ScreenshotLineSpacing {
            get {
                return ((double)(this["ScreenshotLineSpacing"]));
            }
            set {
                this["ScreenshotLineSpacing"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double ScreenshotOutlineWidth {
            get {
                return ((double)(this["ScreenshotOutlineWidth"]));
            }
            set {
                this["ScreenshotOutlineWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScreenshotFontBold {
            get {
                return ((bool)(this["ScreenshotFontBold"]));
            }
            set {
                this["ScreenshotFontBold"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScreenshotDropShadow {
            get {
                return ((bool)(this["ScreenshotDropShadow"]));
            }
            set {
                this["ScreenshotDropShadow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScreenshotEnableBgBox {
            get {
                return ((bool)(this["ScreenshotEnableBgBox"]));
            }
            set {
                this["ScreenshotEnableBgBox"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45")]
        public double ScreenshotBgBoxOpacity {
            get {
                return ((double)(this["ScreenshotBgBoxOpacity"]));
            }
            set {
                this["ScreenshotBgBoxOpacity"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double ScreenshotChatX {
            get {
                return ((double)(this["ScreenshotChatX"]));
            }
            set {
                this["ScreenshotChatX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double ScreenshotChatY {
            get {
                return ((double)(this["ScreenshotChatY"]));
            }
            set {
                this["ScreenshotChatY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300")]
        public int ScreenshotCanvasWidth {
            get {
                return ((int)(this["ScreenshotCanvasWidth"]));
            }
            set {
                this["ScreenshotCanvasWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("730")]
        public int ScreenshotCanvasHeight {
            get {
                return ((int)(this["ScreenshotCanvasHeight"]));
            }
            set {
                this["ScreenshotCanvasHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard RP Thread")]
        public string ScreenshotResolutionPreset {
            get {
                return ((string)(this["ScreenshotResolutionPreset"]));
            }
            set {
                this["ScreenshotResolutionPreset"] = value;
            }
        }
    }
}
