using System;
using System.Text.RegularExpressions;

namespace GTAWParser.Shared
{
    public static class AiTextSanitizer
    {
        public static bool IsMeCommand(string cmdLower) =>
            cmdLower.StartsWith("/me") || cmdLower.StartsWith("/ame") || cmdLower.StartsWith("/melow") || cmdLower.StartsWith("/melong");

        public static bool IsMyCommand(string cmdLower) =>
            cmdLower.StartsWith("/my") || cmdLower.StartsWith("/amy") || cmdLower.StartsWith("/mylow") || cmdLower.StartsWith("/mylong");

        /// <summary>
        /// Normalizes typographic smart quotes, curly apostrophes, and dashes to standard ASCII characters.
        /// </summary>
        public static string NormalizeTypography(string? input)
        {
            if (string.IsNullOrEmpty(input))
                return string.Empty;

            return input
                .Replace('’', '\'')
                .Replace('‘', '\'')
                .Replace('`', '\'')
                .Replace('´', '\'')
                .Replace('ʻ', '\'')
                .Replace('ʼ', '\'')
                .Replace('“', '"')
                .Replace('”', '"')
                .Replace('„', '"')
                .Replace('‟', '"')
                .Replace('«', '"')
                .Replace('»', '"')
                .Replace('—', ' ')
                .Replace('–', ' ')
                .Replace('―', ' ');
        }

        /// <summary>
        /// Cleans, sanitizes, and strips third-person/name redundancy from AI-generated chat responses.
        /// </summary>
        public static string SanitizeResult(string content, string commandPrefix, string originalTextToProcess)
        {
            if (string.IsNullOrWhiteSpace(content))
                return string.Empty;

            string cleaned = content.Trim();

            // 1. Strip reasoning/thinking tags (<think>...</think>) from reasoning models
            cleaned = Regex.Replace(cleaned, @"<think>[\s\S]*?</think>", string.Empty).Trim();
            if (cleaned.Contains("<think>"))
            {
                int idx = cleaned.IndexOf("<think>");
                cleaned = cleaned.Substring(0, idx).Trim();
            }

            // 2. Normalize smart quotes, curly apostrophes, and dashes to standard ASCII
            cleaned = NormalizeTypography(cleaned);

            // 3. Remove enclosing quotes if the model wrapped the response in quotes
            if ((cleaned.StartsWith("\"") && cleaned.EndsWith("\"")) ||
                (cleaned.StartsWith("'") && cleaned.EndsWith("'")))
            {
                cleaned = cleaned.Substring(1, cleaned.Length - 2).Trim();
            }

            if (string.IsNullOrWhiteSpace(cleaned))
                return string.Empty;

            string lowerCmd = (commandPrefix ?? string.Empty).Trim().ToLower();

            // 4. Handle /me and /my formatting and pronoun/name stripping
            if (IsMeCommand(lowerCmd))
            {
                // Strip leading asterisk(s) if generated by model (e.g. "* slides..." or "* Tony Soprano slides...")
                cleaned = Regex.Replace(cleaned, @"^\*+\s*", string.Empty).Trim();

                // Strip leading third-person pronouns or noun phrases (e.g. "He ", "She ", "They ", "The man ", "The figure ")
                cleaned = Regex.Replace(
                    cleaned,
                    @"^(?:he|she|they|the\s+(?:man|woman|guy|girl|figure|person|character|individual))\s+",
                    string.Empty,
                    RegexOptions.IgnoreCase
                ).Trim();

                // Strip leading character name pattern if the model output the persona/character name before the verb
                // (e.g. "Tony Soprano slides...", "John Doe pulls...", "Jack reaches...")
                cleaned = Regex.Replace(
                    cleaned,
                    @"^[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\s+(?=(?:pulls|takes|slides|draws|reaches|grabs|steps|walks|turns|looks|glances|nods|shakes|sighs|smiles|frowns|leans|sits|stands|opens|closes|checks|adjusts|retrieves|places|drops|holds|presses|touches|whispers|speaks|says|mutters|shouts|yells|asks|wonders|thinks|notices|observes|waits|pauses|hesitates|begins|starts|continues|proceeds)\b)",
                    string.Empty
                ).Trim();

                // Strip any remaining leading asterisks
                cleaned = Regex.Replace(cleaned, @"^\*+\s*", string.Empty).Trim();

                if (cleaned.Length > 0 && char.IsUpper(cleaned[0]))
                {
                    cleaned = char.ToLower(cleaned[0]) + cleaned.Substring(1);
                }
            }
            else if (IsMyCommand(lowerCmd))
            {
                // Strip leading asterisk(s)
                cleaned = Regex.Replace(cleaned, @"^\*+\s*", string.Empty).Trim();

                // Strip leading possessive pronouns (e.g. "His ", "Her ", "Their ", "The ")
                cleaned = Regex.Replace(
                    cleaned,
                    @"^(?:his|her|their|the)\s+",
                    string.Empty,
                    RegexOptions.IgnoreCase
                ).Trim();

                // Strip character name possessives (e.g. "Tony Soprano's eyes..." -> "eyes...")
                cleaned = Regex.Replace(
                    cleaned,
                    @"^[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?'s?\s+",
                    string.Empty
                ).Trim();

                if (cleaned.Length > 0 && char.IsUpper(cleaned[0]))
                {
                    cleaned = char.ToLower(cleaned[0]) + cleaned.Substring(1);
                }
            }

            // 5. Enforce finishing punctuation for action commands
            if (!string.IsNullOrWhiteSpace(commandPrefix))
            {
                if (originalTextToProcess.Trim().EndsWith("?") && !cleaned.EndsWith("?"))
                {
                    if (cleaned.EndsWith("."))
                        cleaned = cleaned.Substring(0, cleaned.Length - 1) + "?";
                    else
                        cleaned += "?";
                }
                else if (cleaned.Length > 0 && !cleaned.EndsWith(".") && !cleaned.EndsWith("?") && !cleaned.EndsWith("!"))
                {
                    cleaned += ".";
                }
            }

            return cleaned;
        }
    }
}
